<?php
	echo '<form action="do_agregar_persona.php" class="form-horizontal" id="validation-form" method="post">';
	echo '<div class="control-group">';
	echo '<label class="control-label" for="nombres">Nombres:</label>';
	echo '<div class="controls">';
	echo '<div class="span12">';
	echo '<input type="text" name="nombres" id="nombres" class="input-xlarge" data-rule-required="true" data-rule-minlength="3" />';
	echo '</div>';
	echo '</div>';
	echo '</div>';
	echo '<div class="control-group">';
	echo '<label class="control-label" for="apellidos">Apellidos:</label>';
	echo '<div class="controls">';
	echo '<div class="span12">';
	echo '<input type="text" name="apellidos" id="apellidos" class="input-xlarge" data-rule-required="true" data-rule-minlength="3" />';
	echo '</div>';
	echo '</div>';
	echo '</div>';
	echo '<div class="control-group">';
	echo '<label class="control-label">Fecha de Nacimiento</label>';
	echo '<div class="controls">';
	echo '<div class="input-append date date-picker" data-date="12-02-2012" data-date-format="yyyy-mm-dd" data-date-viewmode="years">';
	echo '<input name="fechanacimiento" class="date-picker" size="16" type="text" value="1980-01-01" /><span class="add-on"><i class="icon-calendar"></i></span>';
	echo '</div>';
	echo '</div>';
	echo '</div>';
	echo '<div class="control-group">';
	echo '<label for="select" class="control-label">Sexo</label>';
	echo '<div class="controls">';
	echo '<select class="input-xlarge" name="sexo" id="sexo" data-rule-required="true">';
	echo '<option value="">-- Please select --</option>';
	echo '<option value="M">Masculino</option>';
	echo '<option value="F">Femenino</option>   ';
	echo '</select>';
	echo '</div>';
	echo '</div>';
	echo '<div class="control-group">';
	echo '<label class="control-label">Foto</label>';
	echo '<div class="controls">';
	echo '<div class="fileupload fileupload-new" data-provides="fileupload">';
	echo '<div class="fileupload-new thumbnail" style="width: 200px; height: 150px;">';
	echo '<img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=no+image" alt="" />';
	echo '</div>';
	echo '<div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"></div>';
	echo '<div>';
	echo '<span class="btn btn-file"><span class="fileupload-new">Select image</span>';
	echo '<span class="fileupload-exists">Change</span>';
	echo '<input type="file" class="default" /></span>';
	echo '<a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remove</a>';
	echo '</div>';
	echo '</div>';
	echo '</div>';
	echo '</div> ';
	echo '<div class="control-group">';
	echo '<div class="controls">';
	echo '<label class="checkbox inline">';
	echo '<input type="checkbox" name="estado" value="true" /> Estado';
	echo '</label>';
	echo '</div>';
	echo '</div>';
	echo '<div class="form-actions">';
	echo '<input type="submit" class="btn btn-primary" value="Agregar">';
	echo ' <button type="button" class="btn">&nbsp;Cancel&nbsp;</button>';
	echo '</div>';
	echo '</form>';
?>